# .streamlit/config.toml

[theme]
primaryColor = "#6c63ff"  # 주요 색상 (버튼, 강조 색상)
backgroundColor = "#f0f2f6"  # 배경 색상
secondaryBackgroundColor = "#ffffff"  # 사이드바 배경 색상
textColor = "#333333"  # 기본 텍스트 색상
font = "sans serif"  # 글꼴 설정 (sans serif, serif, monospace 중 선택)